#!/sbin/busybox sh

cd /
/sbin/busybox mount -t proc proc /proc
/sbin/busybox mount -t sysfs sysfs /sys

/sbin/busybox mkdir -p /dev/block
/sbin/busybox mknod /dev/block/mmcblk0p9 b 259 1
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system

if [ ! -d /system/lib/modules ]; then
	/sbin/busybox mount -o remount,rw /system
	/sbin/busybox mkdir /system/lib/modules
fi;

KV=`busybox uname -r`
CUR=`busybox cat /proc/version`
if busybox [ -e /system/.last_version ]; then
SAV=`busybox cat /system/.last_version`
else
SAV=unknown
fi

if busybox [ "`/busybox grep $KV /system/lib/modules/dhd.ko`" ] && [ "$CUR" == "$SAV" ]; then
    busybox echo "kernel modules already installed, nothing to do"
else
  if busybox [ "$CUR" != "$SAV" ] ; then
    busybox echo $CUR > /system/.last_version
  fi
    busybox rm /system/lib/modules/*
    busybox echo "updating modules..."
    busybox cp /lib/modules/* /system/lib/modules/
fi

/sbin/busybox umount /system
busybox mv -f /init-cyano /init
exec /init
