#!/sbin/busybox sh

BB=/sbin/busybox

cd /

$BB date >>boot.txt
exec >>boot.txt 2>&1

$BB echo "generating mount directories..."
$BB mkdir proc
$BB mkdir sys
$BB mkdir system

$BB mkdir /dev
$BB mkdir /dev/block

$BB mkdir /mnt
$BB chmod 755 /mnt
$BB mkdir /.secondrom

$BB echo "generating device nodes..."
$BB mknod /dev/block/mmcblk0 b 179 0
$BB mknod /dev/block/mmcblk0p13 b 179 13 	# system
$BB mknod /dev/block/mmcblk0p16 b 259 0		# data and .secondrom
$BB mknod /dev/block/loop0 b 7 0

$BB echo "mounting devices..."
$BB mount -t proc proc /proc
$BB mount -t sysfs sysfs /sys

$BB mount -t ext4 /dev/block/mmcblk0p16 /.secondrom

SECONDARYBOOT=0
if $BB [ -f /.secondrom/.secondaryboot ] && $BB [ -f /.secondrom/media/.secondrom/system.img ] ; then
SECONDARYBOOT=`$BB cat /.secondrom/.secondaryboot`
fi

if $BB [ "$SECONDARYBOOT" == 1 ]; then
  $BB mount -t ext4 /.secondrom/media/.secondrom/system.img /system
else
   $BB mount -t ext4 /dev/block/mmcblk0p13 /system
fi

#move .secondrom folder back to the original location if android moved it to a subfolder
if $BB [ -d /.secondrom/media/0/.secondrom ];then
  if $BB [ ! -d /.secondrom/media/.secondrom ];then
    $BB mkdir /.secondrom/media/.secondrom
    $BB mv -f /.secondrom/media/0/.secondrom/* /.secondrom/media/.secondrom
    $BB rmdir /.secondrom/media/0/.secondrom
  fi
fi

CM11=0
CM102=0
SAMMY43=0

if $BB grep -q ro.build.version.release=4.4 /system/build.prop; then
   CM11=1
elif $BB [ -f /system/framework/smartfaceservice.jar ]; then
   SAMMY43=1
else
   CM102=1
fi

if $BB [ ! -f /system/etc/init.d/11setprop ]; then
$BB echo "#!/system/bin/sh" > /system/etc/init.d/11setprop
$BB echo "setprop ro.adb.secure 1" >> /system/etc/init.d/11setprop
$BB echo "setprop ro.secure 1" >> /system/etc/init.d/11setprop
$BB echo "setprop ro.allow.mock.location 0" >> /system/etc/init.d/11setprop
$BB echo "setprop ro.debuggable 1" >> /system/etc/init.d/11setprop
$BB echo "setprop persist.sys.usb.config mtp,adb" >> /system/etc/init.d/11setprop
$BB chmod a+x /system/etc/init.d/11setprop
fi


if [ "$SAMMY43" != 1 ]; then
$BB cp -r -f /misc/mali/* /system/
$BB chown root:root /system/lib/egl/libEGL_mali.so
$BB chown root:root /system/lib/egl/libGLESv1_CM_mali.so
$BB chown root:root /system/lib/egl/libGLESv2_mali.so
$BB chmod 644 /system/lib/egl/libEGL_mali.so
$BB chmod 644 /system/lib/egl/libGLESv1_CM_mali.so
$BB chmod 644 /system/lib/egl/libGLESv2_mali.so
$BB chown root:root /system/lib/libMali.so
$BB chown root:root /system/lib/libUMP.so
$BB chmod 644 /system/lib/libMali.so
$BB chmod 644 /system/lib/libUMP.so
fi


if [ "$CM102" == 1 ]; then
echo "using cm-10.2 initramfs"
$BB mv -f /roms/cm102/* /
   if $BB grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  	# low power mode
 	echo 0 > /proc/sys/kernel/rom_feature_set
 	$BB cp -f lpm.rc init.rc
  	$BB rm -f init.smdk4x12.rc
   else
   	echo 7 > /proc/sys/kernel/rom_feature_set
	$BB mkdir -p /system/lib/modules
	$BB mv /lib/modules/* /system/lib/modules/

	if [ "$SECONDARYBOOT" == "1" ];then
	  echo "secondary boot"
  	  $BB mv /init.mount.rc2 /init.mount.rc
  	  $BB mv /fstab.smdk4x12.2 /fstab.smdk4x12

	  $BB echo "#!/system/bin/sh" > /system/etc/init.d/10sd_mount
	  $BB echo "/system/bin/sdcard /.secondrom/media /mnt/shell/emulated 1023 1023" >> /system/etc/init.d/10sd_mount
	  $BB chmod a+x /system/etc/init.d/10sd_mount
	fi
   fi
elif [ "$CM11" == 1 ]; then
echo "using cm-11 initramfs"
$BB mv -f /roms/cm11/* /
   if $BB grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  	# low power mode
 	echo 0 > /proc/sys/kernel/rom_feature_set
 	$BB cp -f lpm.rc init.rc
  	$BB rm -f init.smdk4x12.rc
   else
   	echo 7 > /proc/sys/kernel/rom_feature_set
	$BB mkdir -p /system/lib/modules
	$BB mv /lib/modules/* /system/lib/modules/

	if [ "$SECONDARYBOOT" == "1" ];then
	  echo "secondary boot"
  	  $BB mv /init.mount.rc2 /init.mount.rc
  	  $BB mv /fstab.smdk4x12.2 /fstab.smdk4x12

	  $BB echo "#!/system/bin/sh" > /system/etc/init.d/10sd_mount
	  $BB echo "/system/bin/sdcard /.secondrom/media /mnt/shell/emulated 1023 1023" >> /system/etc/init.d/10sd_mount
	  $BB chmod a+x /system/etc/init.d/10sd_mount
	fi
   fi
else
echo "using sammy 4.3 initramfs"
$BB mv -f /roms/sammy43/* /
$BB mv -f /misc/sbin2/* /sbin/
$BB mv -f /misc/system/bin/* /system/bin/
$BB chmod a+x /system/bin/sysinit
   if $BB grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  	# low power mode
 	echo 0 > /proc/sys/kernel/rom_feature_set
 	$BB cp -f lpm.rc init.rc
  	$BB rm -f init.smdk4x12.rc
   else
	echo 2 > /proc/sys/kernel/rom_feature_set
	if [ "$SECONDARYBOOT" == "1" ];then
	  echo "secondary boot"
  	  $BB mv /init.mount.rc2 /init.mount.rc
  	  $BB mv /fstab.smdk4x12.2 /fstab.smdk4x12
	fi
   fi
fi

$BB umount -f /system
$BB umount -f /.secondrom

####### cleaning ###########
$BB rm -rf /roms
$BB rm -rf /lib/prop_modules
$BB rm -rf /misc
#############################
exec /sbin/init.2
