#!/sbin/busybox sh

PROFILE=`cat /data/.siyah/.active.profile`;
. /data/.siyah/$PROFILE.profile;

if [ "a$3" == "a" ]; then
	evalcmd='eval "echo \$CPUVOLT$2"';
	eval $evalcmd;
else
	evalcmd='eval "CPUVOLT$2=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$CPUVOLT$2"';
	eval $evalcmd;

	if [ "$cpu_voltage_switch" == on ]; then
		echo "1475000 1450000 1425000 1400000 1375000 1313000 $CPUVOLT1 $CPUVOLT2 $CPUVOLT3 $CPUVOLT4 $CPUVOLT5 $CPUVOLT6 $CPUVOLT7 $CPUVOLT8 $CPUVOLT9 $CPUVOLT10 $CPUVOLT11 $CPUVOLT12 $CPUVOLT13" > /sys/devices/system/cpu/cpu0/cpufreq/UV_uV_table;
	fi;
fi;
